# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e9e9b29f5069af428a1a9f88fd99ca25085ea95492435f08c6f0aa8ad8878b71f4e8d39768150cb10231479659dd7f517b5983febbf736c77afc12b82f71294

test:
  secret_key_base: 4fff0f2c003fde7523583f4851675cc8de2b68432c2100312a549ea1f52b380a22a0fce2fbf1b01ee3efc6bbc82783f5238c7875b2ec8bafc28204c66822bff3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
